### ISSUE TITLE
problem about installing package

### ISSUE THREAD

**Issue by MachineGUN001** [volkamerlab/KinFragLib#44]
!pip install -e KinFragLib

the ERROR occured. 
ERROR: KinFragLib is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).

what's problem and how to fix it up? thanks,

**Comment by MachineGUN001** [comment]
> 
appreciate your kind explanation. Following your process, the KinFragLib can be installed.

the feedback from my system (win10, 64-bit).
(kinfraglib) C:\Users\lenovo>pip install -e KinFragLib
Obtaining file:///C:/Users/lenovo/KinFragLib
  Preparing metadata (setup.py) ... done
Installing collected packages: kinfraglib
  Running setup.py develop for kinfraglib
Successfully installed kinfraglib-1.0.0

however, when I accessed the jupyter lab to open the ipynb in notebook folder as the instruction suggestioned,
the wrong messsage come out as below.

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-d102573dedfa> in <module>
      6 from rdkit.Chem import PandasTools
      7 
----> 8 from kinfraglib import utils

ModuleNotFoundError: No module named 'kinfraglib'

could you please provide some suggestions about how to run the ipynb work well?
many thanks,

S-Y

**Comment by dominiquesydow** [comment]
Hi @MachineGUN001,

This looks to me like the `kinfraglib` module is not installed in the same environment you are running the Jupyter notebook from.

Can you try again, please?
```
conda activate kinfraglib
# Change to folder that contains the `KinFragLib` folder
pip install -e KinFragLib
jupyter lab
```

If that does not work, may I ask you to set up the conda environment again by (1) removing the existing environment with `conda remove --name kinfraglib --all` and (2) following steps 2 and 3 again:
https://github.com/volkamerlab/kinfraglib#quick-start

**Comment by MachineGUN001** [comment]
> Hi @MachineGUN001,
> 
> This looks to me like the `kinfraglib` module is not installed in the same environment you are running the Jupyter notebook from.
> 
> Can you try again, please?
> 
> ```
> conda activate kinfraglib
> # Change to folder that contains the `KinFragLib` folder
> pip install -e KinFragLib
> jupyter lab
> ```
> 
> If that does not work, may I ask you to set up the conda environment again by (1) removing the existing environment with `conda remove --name kinfraglib --all` and (2) following steps 2 and 3 again: https://github.com/volkamerlab/kinfraglib#quick-start

thank you so much!
following your methods, it does work well !~:)
apprecaite that again.

**Comment by dominiquesydow** [comment]
Perfect, happy that it worked! Closing this issue now, feel free to reopen if you run into more issues.
