### ISSUE TITLE
cannot generate n_first_ligands=20000

### ISSUE THREAD

**Issue by MachineGUN001** [volkamerlab/KinFragLib#48]
hi, all,

when I tried to conduct the below cell,

```
%%time 
construct_and_save_ligands_from_combinatorial_library(
    PATH_COMBINATORIAL_LIBRARY, 
    PATH_FRAGMENT_LIBRARY_REDUCED, 
    PATH_CONSTRUCTED_MOLECULES,
    n_first_ligands=20000,
    n_ligands_per_sdf_file=10000
)
```

but the notebooks provided the errors
```
StopIteration                             Traceback (most recent call last)
<timed eval> in <module>

~\AppData\Local\Temp\ipykernel_12788\397085490.py in construct_and_save_ligands_from_combinatorial_library(path_combinatorial_library, path_fragment_library, path_output, n_first_ligands, n_ligands_per_sdf_file)
     44                 # Construct and save ligands
     45                 _construct_and_save_selected_ligands(
---> 46                     ligand_metadata_list, fragment_library, path_output, i
     47                 )
     48                 # Reinitialize ligand metadata list

~\AppData\Local\Temp\ipykernel_12788\1434265608.py in _construct_and_save_selected_ligands(ligand_metadata_list, fragment_library, path_output, index)
     18     ligand_list = [
     19         utils.construct_ligand(ligand["fragment_ids"], ligand["bond_ids"], fragment_library)
---> 20         for ligand in ligand_metadata_list
     21     ]
     22     # Save ligands to file

~\AppData\Local\Temp\ipykernel_12788\1434265608.py in <listcomp>(.0)
     18     ligand_list = [
     19         utils.construct_ligand(ligand["fragment_ids"], ligand["bond_ids"], fragment_library)
---> 20         for ligand in ligand_metadata_list
     21     ]
     22     # Save ligands to file

c:\users\lenovo\kinfraglib\kinfraglib\utils.py in construct_ligand(fragment_ids, bond_ids, fragment_library)
   1299         )
   1300         dummy_2 = next(
-> 1301             atom for atom in combo.GetAtoms() if atom.GetProp("fragment_atom_id") == bond[1]
   1302         )
   1303         atom_1 = dummy_1.GetNeighbors()[0]

StopIteration:
```

I've tried to see, fix the issues and find there are around 560 cpds that were generated by the jupyter notebok procedure.however, accordin to the description of demo use,

```
Construct and save ligands: Example 20k ligands (10k ligands/sdf file) - runtime see below; ~30 MB per file.
```
does that look whether to generate more than 600 ligands under the proces?
many thanks for your kind helps.

best,

![Snipaste_2022-02-09_17-27-28](https://user-images.githubusercontent.com/16698635/153165740-fa0b96f9-fc94-496d-8f62-e50b81ecf93c.png)

**Comment by dominiquesydow** [comment]
Hi @MachineGUN001,

Is this issue still an issue? My apologies for overseeing it for so long. 

It looks like there are no matched atoms in line 1301 ([`StopIteration`](https://docs.python.org/3/library/exceptions.html) is raised by `next()` if there are no elements left in an iterable).

I cannot reproduce the error right now - with the recombination data provided by us (https://zenodo.org/record/3956580), I can run this notebook on Linux and MacOS and it generates SDF files with 10k molecules each. A couple of questions to help me understand your setup:
- Are you using your own data or the KinFragLib dataset (https://zenodo.org/record/3956580)?
- Are you using [this env file](https://github.com/volkamerlab/KinFragLib/blob/master/environment.yml) to create the environment? 
- Which OS are you using?

**Comment by MachineGUN001** [comment]
Thanks for your help in finding the problems, I am currently using Win10 and have installed it using the data and yml environment files provided in your project

Next I will try again to see if it works according to the instructions you provided

best，
