### ISSUE TITLE
Rebuilding the fragment libraries

### ISSUE THREAD

**Issue by mmagithub** [volkamerlab/KinFragLib#50]
Hello,

I am wondering if the tools used to construct the fragments collections are available, I am interested in pulling the fragments from the updated KLIFs repository as well as including other subsets, eg. the DFG-out subset that was not considered in the original publication,

Thanks,
Marawan

**Comment by dominiquesydow** [comment]
Hi @mmagithub,

Thanks for your interest in KinFragLib and my apologies for the slow response.

Please take a look at this repository (README contains usage instructions):
https://github.com/volkamerlab/KinaseFocusedFragmentLibrary
It contains the fragmentation and recombination code that produced the KinFragLib dataset, which is analyzed in this issue's repository.

Please let us know if you need help with the setup/code base (using the other repository's issue functionality, see link above).

I am closing this issue; please do re-open if needed.

Kind regards,
Dominique
