### ISSUE TITLE
KinFragLib dataset update

### ISSUE THREAD

**Issue by peiyaoli** [volkamerlab/KinFragLib#52]
Hi, folks,

Thanks for the contribution on the KinFragLib! It has been 2 years since the release of dataset. I want to know if there is any update on the dataset. Or is there any script I can follow to update by myself?

Best

**Comment by dominiquesydow** [comment]
Hi @peiyaoli,

Thanks a lot for your interest in the library!

Good point indeed, I now started updating the fragment library in #52; the new fragments are now uploaded [here](https://github.com/volkamerlab/KinFragLib/tree/data-v2/data/latest/fragment_library). Recombination and re-analysis of the data will follow.

In case you'd like to run the code yourself, the fragmentation and recombination are done with this code base (input data is a KLIFS download):
https://github.com/volkamerlab/KinaseFocusedFragmentLibrary
(with a couple of code updates in https://github.com/volkamerlab/KinaseFocusedFragmentLibrary/pull/28)

Hope this helps with your work!
