### ISSUE TITLE
Ligands with out-like DFG in KinFragLib

### ISSUE THREAD

**Issue by PaulaKramer** [volkamerlab/KinFragLib#57]
While going through the updated (KLIFS 2023 version) fragment library, I came across fragments in the old/current version, that would not be included in the updated library anymore. Double-checking some of the structures with KLIFS showed that the original ligands have an out-like DFG conformation and are therefore excluded in the new library (see `3efw` and `2bmc` as examples). I haven't checked this for all cases, but this is probably the case for all of the 34 ligands missing in the new library. 

Since only some and not all out-like ligands from KLIFS are included in KinFragLib, I assumed that you also only included structures with DFG-in conformation (as mentioned in the kffl repository). It might be that the DFG conformation in the KLIFS database was changed for those structures? Or do you have another idea why this is the case @dominiquesydow?

**Comment by dominiquesydow** [comment]
Hi @PaulaKramer and @AndreaVolkamer,

My apologies for the late reply, I found this email again in the deep ends of my inbox. 

My first guess as you also mentioned: KLIFS reassigned DFG conformations after our KinFragLib release, so some ligands may have a new assignment now.

See KLIFS news 03-May-2021 https://klifs.net/news.php
> Since the initial creation of the KLIFS classifiers for the DFG and αC-helix, the number of available kinase structures has more than doubled. An update of these classifiers was therefore essential. After iterative rounds of data curation, data generation, and data mining, robust new models were obtained that tremendously improve the classification of the kinase conformation in KLIFS!

This won't have changed most of the conformations but it may have changed some.

**Comment by dominiquesydow** [comment]
@AndreaVolkamer you should be able to find the raw data (KLIFS download folder) on the lab's backup hard drives, you could check that hypothesis there if needed. Let me know if you need help.

**Comment by PaulaKramer** [comment]
Will be solved here: https://github.com/volkamerlab/KinFragLib/pull/58
